-- ATUALIZAR O LOGRADOURO E O COMPLEMENTO DOS ENDEREÇOS COM ID 2 E 3
SELECT * FROM 
VEM_SER.ENDERECO
WHERE id_endereco = 2;

UPDATE VEM_SER.ENDERECO
SET logradouro = 'Comerciante José Miranda de Araújo',
    complemento = 'Apartamento 1004'
WHERE id_endereco = 2;

SELECT * FROM 
VEM_SER.ENDERECO
WHERE id_endereco = 3;

UPDATE VEM_SER.ENDERECO
SET logradouro = 'Hollywood Boulevard',
    complemento = 'Casa B'
WHERE id_endereco = 3;



-- ATUALIZAR O NÚMERO DO ENDEREÇO DE ID 4 PARA 999999
SELECT * FROM 
VEM_SER.ENDERECO
WHERE id_endereco = 4;

UPDATE VEM_SER.ENDERECO
SET numero = 999999
WHERE id_endereco = 4;



-- REMOVER O ÚLTIMO REGISTRO DA TABELA ENDEREÇO (UTILIZANDO A FUNÇÃO MAX)
SELECT MAX(id_endereco) 
FROM VEM_SER.ENDERECO

DELETE FROM VEM_SER.ENDERECO
WHERE id_endereco = 32;



-- REMOVER O ENDEREÇO ONDE O NÚMERO É IGUAL A 999999
SELECT *
FROM VEM_SER.ENDERECO
WHERE numero = 999999;

DELETE FROM VEM_SER.ENDERECO
WHERE numero = 999999;



-- REMOVER 2 REGISTROS DA TABELA ENDEREÇO
SELECT *
FROM VEM_SER.ENDERECO

DELETE FROM VEM_SER.ENDERECO
WHERE id_endereco IN (30, 31);

