-- SELECIONAR TODOS OS PAÍSES ORDENADOS POR NOME DECRESCENTE
SELECT * 
FROM VEM_SER.PAIS
ORDER BY NOME DESC;

SELECT * FROM VEM_SER.ENDERECO 

-- SELECIONAR LOGRADOURO E CEP DOS ENDEREÇOS. PORÉM, SOMENTE OS LOGRADOUROS QUE COMECEM COM A LETRA 'A' (MAIÚSCULO OU MINÚSCULO)
SELECT LOGRADOURO, CEP
FROM VEM_SER.ENDERECO 
WHERE UPPER(LOGRADOURO) LIKE UPPER('a%');

-- SELECIONAR TODOS OS ENDEREÇOS QUE TENHAM CEP COM FINAL '0'
SELECT *
FROM VEM_SER.ENDERECO 
WHERE TRIM(CEP) LIKE '%0';

-- SELECIONAR TODOS OS ENDEREÇOS QUE TENHMA NÚMEROS ENTRE 1 E 100
SELECT *
FROM VEM_SER.ENDERECO 
WHERE NUMERO >= 1 AND NUMERO <= 100;

-- SELECIONAR TODOS OS ENDEREÇOS QUE COMECEM POR "RUA" E ORDENAR PELO CEP DE FORMA DECRESCENTE
SELECT *
FROM VEM_SER.ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'RUA%'
ORDER BY CEP DESC;

-- SELECIONAR A QUANTIDADE DE ENDEREÇOS CADASTRADOS NA TABELA
SELECT COUNT(*) AS quantidade_enderecos
FROM VEM_SER.ENDERECO

-- SELECIONAR A QUANTIDADE DE ENDEREÇOS CADASTRADOS AGRUPADOS PELO ID DA CIDADE
SELECT ID_CIDADE, COUNT(*) AS quantidade_enderecos
FROM VEM_SER.ENDERECO
GROUP BY ID_CIDADE;