-- EXERCÍCIO 1
-- CRIAR TABELA
CREATE TABLE VEM_SER.PESSOA (
id_pessoa NUMBER NOT NULL,
nome VARCHAR2(255) NOT NULL,
data_nascimento DATE NOT NULL,
telefone VARCHAR2(14), -- +5583998022155
idade NUMBER(3) NOT NULL,
altura DECIMAL(4,2) NOT NULL,
cpf CHAR(11) UNIQUE NOT NULL,
PRIMARY KEY(id_pessoa)
);

-- EXERCÍCIO 2
-- CRIAR SEQUENCIA INCREMENTAL AUTOMÁTICA PARA OS INSERT
CREATE SEQUENCE VEM_SER.SEQ_PESSOA
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

-- CRIAR OS INSERTS
INSERT INTO VEM_SER.PESSOA (id_pessoa, nome, data_nascimento, telefone, idade, altura, cpf)
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Pedro Machado', TO_DATE('01-01-1990', 'dd-mm-yyyy'), '51999999999', 30, 1.85, '12345678999');

INSERT INTO VEM_SER.PESSOA (id_pessoa, nome, data_nascimento, telefone, idade, altura, cpf)
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Marcella Araújo', TO_DATE('17-07-1985', 'dd-mm-yyyy'), '83999999999', 39, 1.78, '09912345678');

INSERT INTO VEM_SER.PESSOA (id_pessoa, nome, data_nascimento, telefone, idade, altura, cpf)
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Igor Júnior', TO_DATE('24-08-2012', 'dd-mm-yyyy'), '83999045022', 12, 1.53, '01234567899');

INSERT INTO VEM_SER.PESSOA (id_pessoa, nome, data_nascimento, telefone, idade, altura, cpf)
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Gilma Araújo', TO_DATE('23-03-1963', 'dd-mm-yyyy'), '83996131016', 61, 1.68, '98765432100');

-- SELECIONAR UMA TABELA
SELECT * FROM VEM_SER.PESSOA;

-- ATUALIZAR A IDADE DE TODAS AS PESSOAS DO BANCO DE DADOS COM MAIS 1 ANO
UPDATE VEM_SER.PESSOA
   SET idade = idade + 1;

  -- APAGAR A ÚLTIMA LINHA DO BANCO DE DADOS
 DELETE FROM VEM_SER.PESSOA 
 WHERE id_pessoa = 4;

-- SELECIONAR TODAS AS LINHAS DA TABELA
SELECT * FROM VEM_SER.PESSOA;
   

-- OUTROS COMANDO APRESENTADOS DURANTE A AULA
-- ATUALIZAR DADOS EM UMA TABELA (SEMPRE UTILIZAR O WHERE)
UPDATE VEM_SER.PESSOA
   SET nome = 'Rafael Lazzari'
     , idade = 30
 WHERE id_pessoa = 1;

-- DELETAR DADOS EM UMA TABELA (SEMPRE UTILIZA O WHERE)
DELETE FROM VEM_SER.PESSOA 
 WHERE id_pessoa = 1;

-- SELECIONAR OS DADOS DA TABELA EM ORDEM DECRESCENTE
SELECT * FROM VEM_SER.PESSOA ORDER BY id_pessoa DESC;

-- SELECIONAR OS DADOS DA TABELA EM ORDEM CRESCENTE
SELECT * FROM VEM_SER.PESSOA ORDER BY id_pessoa ASC;


SELECT SEQ_PESSOA.nextval FROM DUAL;
